#!/usr/bin/env python
"""Strip absolute local paths out of the committed split manifests.

The manifest CSVs record which chains belong to which split -- that is their
purpose, and they are committed deliberately. But they currently store rows like

    /home/<user>/Nima/AGAT-PPIS/Dataset/pdb/1f60B.pdb

which publishes a username and a home-directory layout, and will not resolve on
anyone else's machine. This script rewrites the ``path`` column to a
dataset-relative form:

    AGAT-PPIS/Dataset/pdb/1f60B.pdb

Split membership, row order and every other column are preserved exactly, so the
manifests still document the precise splits used for the reported results.

Run this on the REPOSITORY clone, not on your working project directory: the
pipeline scripts consume absolute paths, and your local manifests are
regenerated by ``prepare_benchmark.py`` anyway. Users reproducing the work
regenerate their own manifests with their own paths, as the README describes.

Usage
-----
    python scripts/sanitize_manifests.py --repo-dir .            # dry run
    python scripts/sanitize_manifests.py --repo-dir . --apply
"""
from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

# Everything up to and including a "Dataset/pdb/" style segment is local noise.
ANCHORS = ("AGAT-PPIS/", "DIPS-Plus/", "Dataset/", "data/")


def relativise(p: str) -> str:
    """Return the portion of `p` from the first recognised dataset anchor."""
    p = p.strip().replace("\\", "/")
    for a in ANCHORS:
        i = p.find(a)
        if i != -1:
            return p[i:]
    # No anchor: fall back to the bare filename rather than leaking the tree.
    return p.rsplit("/", 1)[-1]


def looks_absolute(p: str) -> bool:
    return p.startswith("/") or bool(re.match(r"^[A-Za-z]:[\\/]", p))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo-dir", default=".", help="repository root (default: .)")
    ap.add_argument("--apply", action="store_true",
                    help="write the changes (default is a dry run)")
    args = ap.parse_args()

    root = Path(args.repo_dir)
    files = sorted(root.glob("manifests/**/*.csv"))
    if not files:
        sys.exit(f"No manifest CSVs found under {root}/manifests/")

    total_rows = total_changed = 0
    leaked_examples: list[str] = []

    for f in files:
        with f.open(newline="") as fh:
            reader = csv.DictReader(fh)
            fields = reader.fieldnames or []
            rows = list(reader)
        if "path" not in fields:
            print(f"  [skip] {f.relative_to(root)}: no 'path' column")
            continue

        changed = 0
        for r in rows:
            old = r["path"]
            new = relativise(old)
            if new != old:
                changed += 1
                if looks_absolute(old) and len(leaked_examples) < 3:
                    leaked_examples.append(f"{old}  ->  {new}")
                r["path"] = new
        total_rows += len(rows)
        total_changed += changed

        status = "would rewrite" if not args.apply else "rewrote"
        print(f"  {status} {changed:4d}/{len(rows):4d} rows in {f.relative_to(root)}")

        if args.apply and changed:
            tmp = f.with_suffix(".csv.tmp")
            with tmp.open("w", newline="") as fh:
                w = csv.DictWriter(fh, fieldnames=fields)
                w.writeheader()
                w.writerows(rows)
            tmp.replace(f)

    print(f"\n{total_changed} of {total_rows} rows across {len(files)} manifest(s)")
    if leaked_examples:
        print("\nExamples of what is being removed:")
        for e in leaked_examples:
            print(f"  {e}")
    if not args.apply:
        print("\nDry run only. Re-run with --apply to write the changes.")
    else:
        print("\nDone. Verify with:")
        print("  grep -rn '/home/' manifests/ || echo 'no absolute paths remain'")


if __name__ == "__main__":
    main()
